WITH J_CP AS (
    SELECT FLAVOR
         , SUM(TOTAL_ORDER) AS TOTAL
    FROM JULY
    GROUP BY FLAVOR
)
SELECT F.FLAVOR
  FROM FIRST_HALF F
 INNER JOIN J_CP JC
    ON (F.FLAVOR = JC.FLAVOR)
 GROUP BY FLAVOR
 ORDER BY SUM(F.TOTAL_ORDER + JC.TOTAL) DESC
 LIMIT 3
;