SELECT FLAVOR
FROM(
    SELECT FLAVOR
     , SUM(TOTAL_ORDER) AS TOTAL_F
    FROM FIRST_HALF
    GROUP BY FLAVOR
    UNION
    SELECT FLAVOR
     , SUM(TOTAL_ORDER)
    FROM JULY
    GROUP BY FLAVOR
) A
GROUP BY FLAVOR
ORDER BY SUM(A.TOTAL_F) DESC
LIMIT 3
;
